/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import Tabelas.Raca;
import conexao.ConexaoBanco;
import dao.GenericDAO;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.lang.reflect.InvocationTargetException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tabelas.Classes;
import tabelas.Personagens;

/**
 *
 * @author Adriel
 */
public class JFPersonagem extends javax.swing.JFrame {
    
    public void centralizarComponente() {
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw = getSize();
        setLocation((ds.width - dw.width) / 2,
                (ds.height - dw.height) / 2);
    }
    //declaração de variaveis
    int forca;
    int destreza;
    int constituicao;
    int inteligencia;
    int sabedoria;
    int carisma;
    //arraylist
    ArrayList listRaca = new ArrayList();
    ArrayList listClasse = new ArrayList();

    /**
     * Creates new form JFPersonagem
     */
    public JFPersonagem() {
        initComponents();
        centralizarComponente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfNomePersonagem = new javax.swing.JTextField();
        jCClasse = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jtfIdadePersonagem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfPesoPersonagem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfAlturaPersonagem = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtfForcaPersonagem = new javax.swing.JTextField();
        jtfDestrezaPersonagem = new javax.swing.JTextField();
        jtfConstituicaoPersonagem = new javax.swing.JTextField();
        jtfInteligenciaPersonagem = new javax.swing.JTextField();
        jtfSabedoriaPersonagem = new javax.swing.JTextField();
        jtfCarismaPersonagem = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfFortitudePersonagem = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtfRefexoPersonagem = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtfVontadePersonagem = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtfClasseArmaduraPersonagem = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtfPontosDeVidaPersonagem = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtfIniciativaPersonagem = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jtfBaseDeAtaquePersonagem = new javax.swing.JTextField();
        jBSalvar = new javax.swing.JButton();
        jCRaca = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("Idade");

        jtfIdadePersonagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfIdadePersonagemKeyTyped(evt);
            }
        });

        jLabel3.setText("Peso");

        jtfPesoPersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPesoPersonagemActionPerformed(evt);
            }
        });
        jtfPesoPersonagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfPesoPersonagemKeyTyped(evt);
            }
        });

        jLabel4.setText("Altura");

        jtfAlturaPersonagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfAlturaPersonagemKeyTyped(evt);
            }
        });

        jLabel5.setText("Força");

        jLabel6.setText("Destreza");

        jLabel7.setText("Constituição");

        jLabel8.setText("Inteligência");

        jLabel9.setText("Sabedoria");

        jLabel10.setText("Carisma");

        jtfForcaPersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfForcaPersonagemActionPerformed(evt);
            }
        });
        jtfForcaPersonagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfForcaPersonagemKeyTyped(evt);
            }
        });

        jtfDestrezaPersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDestrezaPersonagemActionPerformed(evt);
            }
        });
        jtfDestrezaPersonagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfDestrezaPersonagemKeyTyped(evt);
            }
        });

        jtfConstituicaoPersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfConstituicaoPersonagemActionPerformed(evt);
            }
        });
        jtfConstituicaoPersonagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfConstituicaoPersonagemKeyTyped(evt);
            }
        });

        jtfInteligenciaPersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfInteligenciaPersonagemActionPerformed(evt);
            }
        });
        jtfInteligenciaPersonagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfInteligenciaPersonagemKeyTyped(evt);
            }
        });

        jtfSabedoriaPersonagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfSabedoriaPersonagemKeyTyped(evt);
            }
        });

        jtfCarismaPersonagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCarismaPersonagemKeyTyped(evt);
            }
        });

        jLabel11.setText("Fortitude");

        jtfFortitudePersonagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfFortitudePersonagemKeyTyped(evt);
            }
        });

        jLabel13.setText("Refexos");

        jtfRefexoPersonagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfRefexoPersonagemKeyTyped(evt);
            }
        });

        jLabel14.setText("Vontade");

        jtfVontadePersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfVontadePersonagemActionPerformed(evt);
            }
        });
        jtfVontadePersonagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfVontadePersonagemKeyTyped(evt);
            }
        });

        jLabel15.setText("Cls.Armadura (CA)");

        jtfClasseArmaduraPersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfClasseArmaduraPersonagemActionPerformed(evt);
            }
        });
        jtfClasseArmaduraPersonagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfClasseArmaduraPersonagemKeyTyped(evt);
            }
        });

        jLabel16.setText("Pontos de Vida");

        jtfPontosDeVidaPersonagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfPontosDeVidaPersonagemKeyTyped(evt);
            }
        });

        jLabel17.setText("Iniciativa");

        jtfIniciativaPersonagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfIniciativaPersonagemKeyTyped(evt);
            }
        });

        jLabel18.setText("Base de Ataque");

        jtfBaseDeAtaquePersonagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfBaseDeAtaquePersonagemKeyTyped(evt);
            }
        });

        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        jLabel19.setText("Classe");

        jLabel20.setText("Raça");

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel20)
                .addGap(7, 7, 7)
                .addComponent(jCRaca, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(jLabel12)
                .addGap(12, 12, 12)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jCClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addComponent(jtfNomePersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jtfClasseArmaduraPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(17, 17, 17)
                .addComponent(jtfIdadePersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jtfBaseDeAtaquePersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addGap(17, 17, 17)
                .addComponent(jtfPesoPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jtfPontosDeVidaPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfAlturaPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfForcaPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel14)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfIniciativaPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfVontadePersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(17, 17, 17)
                .addComponent(jtfDestrezaPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jtfRefexoPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jtfConstituicaoPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jtfCarismaPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addGap(17, 17, 17)
                .addComponent(jtfInteligenciaPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addGap(17, 17, 17)
                .addComponent(jtfSabedoriaPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(jBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11)
                .addGap(17, 17, 17)
                .addComponent(jtfFortitudePersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel20))
                    .addComponent(jCRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel19))
                    .addComponent(jCClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1))
                    .addComponent(jtfNomePersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel15))
                    .addComponent(jtfClasseArmaduraPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfIdadePersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfBaseDeAtaquePersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel18))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(jtfPesoPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel16))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jtfPontosDeVidaPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfAlturaPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jtfForcaPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel17)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jtfIniciativaPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jtfVontadePersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jtfDestrezaPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jtfRefexoPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7))
                    .addComponent(jtfConstituicaoPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jtfCarismaPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jtfInteligenciaPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9))
                    .addComponent(jtfSabedoriaPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jBSalvar)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jtfFortitudePersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButton1))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPesoPersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPesoPersonagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPesoPersonagemActionPerformed

    private void jtfDestrezaPersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDestrezaPersonagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDestrezaPersonagemActionPerformed

    private void jtfConstituicaoPersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfConstituicaoPersonagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfConstituicaoPersonagemActionPerformed

    private void jtfInteligenciaPersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfInteligenciaPersonagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfInteligenciaPersonagemActionPerformed

    private void jtfClasseArmaduraPersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfClasseArmaduraPersonagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfClasseArmaduraPersonagemActionPerformed

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed

        try {

            if (jtfAlturaPersonagem.getText().equals("")    ||      jtfBaseDeAtaquePersonagem.getText().equals("")    ||   jtfCarismaPersonagem.getText().equals("")||jtfClasseArmaduraPersonagem.getText().equals("")||jtfConstituicaoPersonagem.getText().equals("")||jtfDestrezaPersonagem.getText().equals("")||jtfForcaPersonagem.getText().equals("") || jtfFortitudePersonagem.getText().equals("") || jtfIdadePersonagem.getText().equals("") || jtfIniciativaPersonagem.getText().equals("") || jtfInteligenciaPersonagem.getText().equals("") || jtfNomePersonagem.getText().equals("") || jtfPesoPersonagem.getText().equals("") || jtfPontosDeVidaPersonagem.getText().equals("") || jtfRefexoPersonagem.getText().equals(""
                    + "") || jtfSabedoriaPersonagem.getText().equals("")|| jtfVontadePersonagem.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Favor Preencher todos os campos!");

            } else {
                GenericDAO aDao = new GenericDAO();

                Personagens pers = new Personagens();
                Raca rc = new Raca();

                rc.setCodigo_raca((int) listRaca.get(jCRaca.getSelectedIndex()));   //pega os atributos da raça
                List<Object> list = aDao.listar2(Raca.class, rc);                   //que o jogador escolheu
                for (Object obj3 : list) {                                          //<--
                                                                                    //<--
                    Raca r = (Raca) obj3;                                           //<--
                                                                                    //<--
                    forca = (r.getForca_raca());                                    //<--
                    destreza = (r.getDestreza_raca());                              //<--
                    constituicao = (r.getConstituicao_raca());                      //<--
                    inteligencia = (r.getInteligencia_raca());                      //<--
                    sabedoria = (r.getSabedoria_raca());                            //<--
                    carisma = (r.getCarisma_raca());                                //<--
                }

                pers.setNome_personagem("");
                pers.setIdade_personagem(0);
                pers.setPeso_personagem(0);
                pers.setAltura_personagem(0);
                pers.setForca_personagem(0);
                pers.setForca_personagem(0);
                pers.setDestreza_personagem(0);
                pers.setContituicao_personagem(0);
                pers.setInteligencia_personagem(0);
                pers.setSabedoria_personagem(0);
                pers.setCarisma_personagem(0);
                pers.setFortitude_personagem(0);
                pers.setReflexos_personagem(0);
                pers.setVontade_personagem(0);
                pers.setClasse_armadura_personagem(0);
                pers.setPontos_vida_personagem(0);
                pers.setIniciativa_personagem(0);
                pers.setBase_ataque_personagem(0);

                //seta os atributos do personagem no BD de acordo com que o jogador escolher + o que o personagem ganha da classe
                pers.setNome_personagem(jtfNomePersonagem.getText());
                pers.setIdade_personagem(Integer.parseInt(jtfIdadePersonagem.getText()));
                pers.setPeso_personagem(Integer.parseInt(jtfPesoPersonagem.getText()));
                pers.setAltura_personagem(Integer.parseInt(jtfAlturaPersonagem.getText()));
                pers.setForca_personagem(forca + (Integer.parseInt(jtfForcaPersonagem.getText())));
                pers.setDestreza_personagem(destreza + (Integer.parseInt(jtfDestrezaPersonagem.getText())));
                pers.setContituicao_personagem(constituicao + (Integer.parseInt(jtfConstituicaoPersonagem.getText())));
                pers.setInteligencia_personagem(inteligencia + (Integer.parseInt(jtfInteligenciaPersonagem.getText())));
                pers.setSabedoria_personagem(sabedoria + (Integer.parseInt(jtfSabedoriaPersonagem.getText())));
                pers.setCarisma_personagem(carisma + (Integer.parseInt(jtfCarismaPersonagem.getText())));
                pers.setFortitude_personagem(Integer.parseInt(jtfFortitudePersonagem.getText()));
                pers.setReflexos_personagem(Integer.parseInt(jtfRefexoPersonagem.getText()));
                pers.setVontade_personagem(Integer.parseInt(jtfVontadePersonagem.getText()));
                pers.setClasse_armadura_personagem(Integer.parseInt(jtfClasseArmaduraPersonagem.getText()));
                pers.setPontos_vida_personagem(Integer.parseInt(jtfPontosDeVidaPersonagem.getText()));
                pers.setIniciativa_personagem(Integer.parseInt(jtfIniciativaPersonagem.getText()));
                pers.setBase_ataque_personagem(Integer.parseInt(jtfBaseDeAtaquePersonagem.getText()));
                pers.setCodigo_raca((int) listRaca.get(jCRaca.getSelectedIndex()));
                pers.setCodigo_classe((int) listClasse.get(jCClasse.getSelectedIndex()));

                aDao.adicionar(pers);
             JFPersonagem.this.dispose();

            }
        } catch (SQLException ex) {
            Logger.getLogger(JFPersonagem.class.getName()).log(Level.SEVERE, null, ex);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JFPersonagem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(JFPersonagem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(JFPersonagem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchMethodException ex) {
            Logger.getLogger(JFPersonagem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvocationTargetException ex) {
            Logger.getLogger(JFPersonagem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(JFPersonagem.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jBSalvarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        GenericDAO aDao;
        try {            
            aDao = new GenericDAO();
            
            List<Object> list = aDao.listar(Classes.class);// listar generico

            for (Object obj2 : list) {

                Classes cl = (Classes) obj2;

                String Classe = "";
                Classe = cl.getNome_classe();
                jCClasse.addItem(Classe);// adiciona nome da classe no comboBox
                listClasse.add(cl.getCodigo_classe());//adiciona o codigo da classe no array classe

            }

            List<Object> list2 = aDao.listar(Raca.class);

            for (Object obj2 : list2) {

                Raca rc = (Raca) obj2;
                String Raca = "";
                Raca = rc.getNome_raca();
                jCRaca.addItem(Raca);// adiciona o nome da raca no comboBox
                listRaca.add(rc.getCodigo_raca());//adiciona o codigo da raca no array raca
            }

        } catch (SQLException ex) {
            Logger.getLogger(JFPersonagem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(JFPersonagem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchMethodException ex) {
            Logger.getLogger(JFPersonagem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(JFPersonagem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvocationTargetException ex) {
            Logger.getLogger(JFPersonagem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(JFPersonagem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JFPersonagem.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jtfVontadePersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfVontadePersonagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfVontadePersonagemActionPerformed

    private void jtfForcaPersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfForcaPersonagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfForcaPersonagemActionPerformed

    private void jtfForcaPersonagemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfForcaPersonagemKeyTyped
 String caracteres = "0987654321 "; //apenas numeros podem ser digitados
        if (!caracteres.contains(evt.getKeyChar() + "")) { //se algo diferente que "caracteres" for digitado
            evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_jtfForcaPersonagemKeyTyped

    private void jtfIdadePersonagemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIdadePersonagemKeyTyped
 String caracteres = "0987654321 "; //apenas numeros podem ser digitados
        if (!caracteres.contains(evt.getKeyChar() + "")) { //se algo diferente que "caracteres" for digitado
            evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIdadePersonagemKeyTyped

    private void jtfPesoPersonagemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesoPersonagemKeyTyped
 String caracteres = "0987654321 "; //apenas numeros podem ser digitados
        if (!caracteres.contains(evt.getKeyChar() + "")) { //se algo diferente que "caracteres" for digitado
            evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPesoPersonagemKeyTyped

    private void jtfAlturaPersonagemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAlturaPersonagemKeyTyped
 String caracteres = "0987654321 "; //apenas numeros podem ser digitados
        if (!caracteres.contains(evt.getKeyChar() + "")) { //se algo diferente que "caracteres" for digitado
            evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAlturaPersonagemKeyTyped

    private void jtfDestrezaPersonagemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDestrezaPersonagemKeyTyped
 String caracteres = "0987654321 "; //apenas numeros podem ser digitados
        if (!caracteres.contains(evt.getKeyChar() + "")) { //se algo diferente que "caracteres" for digitado
            evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDestrezaPersonagemKeyTyped

    private void jtfConstituicaoPersonagemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfConstituicaoPersonagemKeyTyped
 String caracteres = "0987654321 "; //apenas numeros podem ser digitados
        if (!caracteres.contains(evt.getKeyChar() + "")) { //se algo diferente que "caracteres" for digitado
            evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_jtfConstituicaoPersonagemKeyTyped

    private void jtfInteligenciaPersonagemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfInteligenciaPersonagemKeyTyped
 String caracteres = "0987654321 "; //apenas numeros podem ser digitados
        if (!caracteres.contains(evt.getKeyChar() + "")) { //se algo diferente que "caracteres" for digitado
            evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_jtfInteligenciaPersonagemKeyTyped

    private void jtfSabedoriaPersonagemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSabedoriaPersonagemKeyTyped
 String caracteres = "0987654321 "; //apenas numeros podem ser digitados
        if (!caracteres.contains(evt.getKeyChar() + "")) { //se algo diferente que "caracteres" for digitado
            evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSabedoriaPersonagemKeyTyped

    private void jtfFortitudePersonagemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFortitudePersonagemKeyTyped
 String caracteres = "0987654321 "; //apenas numeros podem ser digitados
        if (!caracteres.contains(evt.getKeyChar() + "")) { //se algo diferente que "caracteres" for digitado
            evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFortitudePersonagemKeyTyped

    private void jtfClasseArmaduraPersonagemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfClasseArmaduraPersonagemKeyTyped
 String caracteres = "0987654321 "; //apenas numeros podem ser digitados
        if (!caracteres.contains(evt.getKeyChar() + "")) { //se algo diferente que "caracteres" for digitado
            evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_jtfClasseArmaduraPersonagemKeyTyped

    private void jtfBaseDeAtaquePersonagemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBaseDeAtaquePersonagemKeyTyped
 String caracteres = "0987654321 "; //apenas numeros podem ser digitados
        if (!caracteres.contains(evt.getKeyChar() + "")) { //se algo diferente que "caracteres" for digitado
            evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_jtfBaseDeAtaquePersonagemKeyTyped

    private void jtfPontosDeVidaPersonagemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPontosDeVidaPersonagemKeyTyped
 String caracteres = "0987654321 "; //apenas numeros podem ser digitados
        if (!caracteres.contains(evt.getKeyChar() + "")) { //se algo diferente que "caracteres" for digitado
            evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPontosDeVidaPersonagemKeyTyped

    private void jtfIniciativaPersonagemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIniciativaPersonagemKeyTyped
 String caracteres = "0987654321 "; //apenas numeros podem ser digitados
        if (!caracteres.contains(evt.getKeyChar() + "")) { //se algo diferente que "caracteres" for digitado
            evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIniciativaPersonagemKeyTyped

    private void jtfVontadePersonagemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfVontadePersonagemKeyTyped
 String caracteres = "0987654321 "; //apenas numeros podem ser digitados
        if (!caracteres.contains(evt.getKeyChar() + "")) { //se algo diferente que "caracteres" for digitado
            evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_jtfVontadePersonagemKeyTyped

    private void jtfRefexoPersonagemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfRefexoPersonagemKeyTyped
 String caracteres = "0987654321 "; //apenas numeros podem ser digitados
        if (!caracteres.contains(evt.getKeyChar() + "")) { //se algo diferente que "caracteres" for digitado
            evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_jtfRefexoPersonagemKeyTyped

    private void jtfCarismaPersonagemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCarismaPersonagemKeyTyped
 String caracteres = "0987654321 "; //apenas numeros podem ser digitados
        if (!caracteres.contains(evt.getKeyChar() + "")) { //se algo diferente que "caracteres" for digitado
            evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCarismaPersonagemKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jtfNomePersonagem.setText(null);
        jtfAlturaPersonagem.setText(null);
        jtfBaseDeAtaquePersonagem.setText(null);
        jtfCarismaPersonagem.setText(null);
        jtfClasseArmaduraPersonagem.setText(null);
        jtfConstituicaoPersonagem.setText(null);
        jtfDestrezaPersonagem.setText(null);
        jtfForcaPersonagem.setText(null);
        jtfFortitudePersonagem.setText(null);
        jtfIdadePersonagem.setText(null);
        jtfIniciativaPersonagem.setText(null);
        jtfInteligenciaPersonagem.setText(null);
        jtfPesoPersonagem.setText(null);
        jtfPontosDeVidaPersonagem.setText(null);
        jtfRefexoPersonagem.setText(null);
        jtfSabedoriaPersonagem.setText(null);
        jtfVontadePersonagem.setText(null);
        JFPersonagem.this.dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPersonagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jCClasse;
    private javax.swing.JComboBox jCRaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jtfAlturaPersonagem;
    private javax.swing.JTextField jtfBaseDeAtaquePersonagem;
    private javax.swing.JTextField jtfCarismaPersonagem;
    private javax.swing.JTextField jtfClasseArmaduraPersonagem;
    private javax.swing.JTextField jtfConstituicaoPersonagem;
    private javax.swing.JTextField jtfDestrezaPersonagem;
    private javax.swing.JTextField jtfForcaPersonagem;
    private javax.swing.JTextField jtfFortitudePersonagem;
    private javax.swing.JTextField jtfIdadePersonagem;
    private javax.swing.JTextField jtfIniciativaPersonagem;
    private javax.swing.JTextField jtfInteligenciaPersonagem;
    private javax.swing.JTextField jtfNomePersonagem;
    private javax.swing.JTextField jtfPesoPersonagem;
    private javax.swing.JTextField jtfPontosDeVidaPersonagem;
    private javax.swing.JTextField jtfRefexoPersonagem;
    private javax.swing.JTextField jtfSabedoriaPersonagem;
    private javax.swing.JTextField jtfVontadePersonagem;
    // End of variables declaration//GEN-END:variables
}
