/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author Felipe Ittner
 */
public class JFTrocaItens extends javax.swing.JFrame {

    /**
     * Creates new form JFTrocaCliente
     */
    public JFTrocaItens() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcComprarArmas = new javax.swing.JComboBox();
        jcVenderArmas = new javax.swing.JComboBox();
        jcComprarArmaduras = new javax.swing.JComboBox();
        jcComprarEscudos = new javax.swing.JComboBox();
        jcComprarConsumiveis = new javax.swing.JComboBox();
        jcVenderArmaduras = new javax.swing.JComboBox();
        jcVenderEscudos = new javax.swing.JComboBox();
        jcVenderConsumiveis = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jcbComprarArmas = new javax.swing.JCheckBox();
        jcbComprarArmaduras = new javax.swing.JCheckBox();
        jcbComprarEscudos = new javax.swing.JCheckBox();
        jcbComprarConsumiveis = new javax.swing.JCheckBox();
        jcbVenderArmas = new javax.swing.JCheckBox();
        jcbVenderArmaduras = new javax.swing.JCheckBox();
        jcbVenderEscudos = new javax.swing.JCheckBox();
        jcbVenderConsumiveis = new javax.swing.JCheckBox();
        lbVender = new javax.swing.JLabel();
        jlListPreçoTotalComprar = new javax.swing.JLabel();
        lbVender1 = new javax.swing.JLabel();
        jlListPreçoTotalComprar1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jcComprarArmas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcComprarArmasItemStateChanged(evt);
            }
        });
        jcComprarArmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcComprarArmasActionPerformed(evt);
            }
        });

        jcVenderArmas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcVenderArmasItemStateChanged(evt);
            }
        });
        jcVenderArmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcVenderArmasActionPerformed(evt);
            }
        });

        jcComprarArmaduras.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcComprarArmadurasItemStateChanged(evt);
            }
        });
        jcComprarArmaduras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcComprarArmadurasActionPerformed(evt);
            }
        });

        jcComprarEscudos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcComprarEscudosItemStateChanged(evt);
            }
        });
        jcComprarEscudos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcComprarEscudosActionPerformed(evt);
            }
        });

        jcComprarConsumiveis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcComprarConsumiveisItemStateChanged(evt);
            }
        });
        jcComprarConsumiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcComprarConsumiveisActionPerformed(evt);
            }
        });

        jcVenderArmaduras.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcVenderArmadurasItemStateChanged(evt);
            }
        });

        jcVenderEscudos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcVenderEscudosItemStateChanged(evt);
            }
        });

        jcVenderConsumiveis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcVenderConsumiveisItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel1.setText("Tela de Troca");

        jcbComprarArmas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbComprarArmas.setText("Armas");
        jcbComprarArmas.setHideActionText(true);
        jcbComprarArmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbComprarArmasActionPerformed(evt);
            }
        });

        jcbComprarArmaduras.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbComprarArmaduras.setText("Armaduras");
        jcbComprarArmaduras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbComprarArmadurasActionPerformed(evt);
            }
        });

        jcbComprarEscudos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbComprarEscudos.setText("Escudos");
        jcbComprarEscudos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbComprarEscudosActionPerformed(evt);
            }
        });

        jcbComprarConsumiveis.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbComprarConsumiveis.setText("Consumiveis");
        jcbComprarConsumiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbComprarConsumiveisActionPerformed(evt);
            }
        });

        jcbVenderArmas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbVenderArmas.setText("Armas");
        jcbVenderArmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbVenderArmasActionPerformed(evt);
            }
        });

        jcbVenderArmaduras.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbVenderArmaduras.setText("Armaduras");
        jcbVenderArmaduras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbVenderArmadurasActionPerformed(evt);
            }
        });

        jcbVenderEscudos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbVenderEscudos.setText("Escudos");
        jcbVenderEscudos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbVenderEscudosActionPerformed(evt);
            }
        });

        jcbVenderConsumiveis.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbVenderConsumiveis.setText("Consumiveis");
        jcbVenderConsumiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbVenderConsumiveisActionPerformed(evt);
            }
        });

        lbVender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbVender.setText("Personagem:");

        lbVender1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbVender1.setText("Personagem:");

        jCheckBox1.setText("Confirmar");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Confirmar");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlListPreçoTotalComprar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbVender1)
                        .addGap(52, 52, 52)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlListPreçoTotalComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbVender)
                        .addGap(131, 131, 131))))
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcbComprarArmaduras)
                        .addGap(11, 11, 11)
                        .addComponent(jcComprarArmaduras, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jcbVenderArmaduras)
                        .addGap(11, 11, 11)
                        .addComponent(jcVenderArmaduras, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcbComprarEscudos)
                        .addGap(29, 29, 29)
                        .addComponent(jcComprarEscudos, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jcbVenderEscudos)
                        .addGap(29, 29, 29)
                        .addComponent(jcVenderEscudos, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcbComprarConsumiveis)
                        .addGap(3, 3, 3)
                        .addComponent(jcComprarConsumiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jcbVenderConsumiveis)
                        .addGap(3, 3, 3)
                        .addComponent(jcVenderConsumiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcbComprarArmas)
                        .addGap(37, 37, 37)
                        .addComponent(jcComprarArmas, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jcbVenderArmas)
                        .addGap(37, 37, 37)
                        .addComponent(jcVenderArmas, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox1)
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbVender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlListPreçoTotalComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbVender1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlListPreçoTotalComprar1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbComprarArmas)
                    .addComponent(jcComprarArmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbVenderArmas)
                    .addComponent(jcVenderArmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbComprarArmaduras)
                    .addComponent(jcComprarArmaduras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbVenderArmaduras)
                    .addComponent(jcVenderArmaduras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbComprarEscudos)
                    .addComponent(jcComprarEscudos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbVenderEscudos)
                    .addComponent(jcVenderEscudos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbComprarConsumiveis)
                    .addComponent(jcComprarConsumiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbVenderConsumiveis)
                    .addComponent(jcVenderConsumiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcComprarArmasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcComprarArmasItemStateChanged

    }//GEN-LAST:event_jcComprarArmasItemStateChanged

    private void jcComprarArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcComprarArmasActionPerformed

    }//GEN-LAST:event_jcComprarArmasActionPerformed

    private void jcVenderArmasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcVenderArmasItemStateChanged

    }//GEN-LAST:event_jcVenderArmasItemStateChanged

    private void jcVenderArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcVenderArmasActionPerformed

    }//GEN-LAST:event_jcVenderArmasActionPerformed

    private void jcComprarArmadurasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcComprarArmadurasItemStateChanged

    }//GEN-LAST:event_jcComprarArmadurasItemStateChanged

    private void jcComprarArmadurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcComprarArmadurasActionPerformed

    }//GEN-LAST:event_jcComprarArmadurasActionPerformed

    private void jcComprarEscudosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcComprarEscudosItemStateChanged

    }//GEN-LAST:event_jcComprarEscudosItemStateChanged

    private void jcComprarEscudosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcComprarEscudosActionPerformed

    }//GEN-LAST:event_jcComprarEscudosActionPerformed

    private void jcComprarConsumiveisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcComprarConsumiveisItemStateChanged

    }//GEN-LAST:event_jcComprarConsumiveisItemStateChanged

    private void jcComprarConsumiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcComprarConsumiveisActionPerformed

    }//GEN-LAST:event_jcComprarConsumiveisActionPerformed

    private void jcVenderArmadurasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcVenderArmadurasItemStateChanged

    }//GEN-LAST:event_jcVenderArmadurasItemStateChanged

    private void jcVenderEscudosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcVenderEscudosItemStateChanged

    }//GEN-LAST:event_jcVenderEscudosItemStateChanged

    private void jcVenderConsumiveisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcVenderConsumiveisItemStateChanged

    }//GEN-LAST:event_jcVenderConsumiveisItemStateChanged

    private void jcbComprarArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbComprarArmasActionPerformed

    }//GEN-LAST:event_jcbComprarArmasActionPerformed

    private void jcbComprarArmadurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbComprarArmadurasActionPerformed

    }//GEN-LAST:event_jcbComprarArmadurasActionPerformed

    private void jcbComprarEscudosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbComprarEscudosActionPerformed

    }//GEN-LAST:event_jcbComprarEscudosActionPerformed

    private void jcbComprarConsumiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbComprarConsumiveisActionPerformed

    }//GEN-LAST:event_jcbComprarConsumiveisActionPerformed

    private void jcbVenderArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbVenderArmasActionPerformed

    }//GEN-LAST:event_jcbVenderArmasActionPerformed

    private void jcbVenderArmadurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbVenderArmadurasActionPerformed

    }//GEN-LAST:event_jcbVenderArmadurasActionPerformed

    private void jcbVenderEscudosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbVenderEscudosActionPerformed

    }//GEN-LAST:event_jcbVenderEscudosActionPerformed

    private void jcbVenderConsumiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbVenderConsumiveisActionPerformed

    }//GEN-LAST:event_jcbVenderConsumiveisActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed

    }//GEN-LAST:event_jCheckBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFTrocaItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFTrocaItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFTrocaItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFTrocaItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFTrocaItens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox jcComprarArmaduras;
    private javax.swing.JComboBox jcComprarArmas;
    private javax.swing.JComboBox jcComprarConsumiveis;
    private javax.swing.JComboBox jcComprarEscudos;
    private javax.swing.JComboBox jcVenderArmaduras;
    private javax.swing.JComboBox jcVenderArmas;
    private javax.swing.JComboBox jcVenderConsumiveis;
    private javax.swing.JComboBox jcVenderEscudos;
    private javax.swing.JCheckBox jcbComprarArmaduras;
    private javax.swing.JCheckBox jcbComprarArmas;
    private javax.swing.JCheckBox jcbComprarConsumiveis;
    private javax.swing.JCheckBox jcbComprarEscudos;
    private javax.swing.JCheckBox jcbVenderArmaduras;
    private javax.swing.JCheckBox jcbVenderArmas;
    private javax.swing.JCheckBox jcbVenderConsumiveis;
    private javax.swing.JCheckBox jcbVenderEscudos;
    private javax.swing.JLabel jlListPreçoTotalComprar;
    private javax.swing.JLabel jlListPreçoTotalComprar1;
    private javax.swing.JLabel lbVender;
    private javax.swing.JLabel lbVender1;
    // End of variables declaration//GEN-END:variables
}
