/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import dao.GenericDAO;
import java.lang.reflect.InvocationTargetException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import tabelas.Armaduras;
import tabelas.Armas;
import tabelas.Consumiveis;
import tabelas.Escudos;
import tabelas.PersonagensArmaduras;
import tabelas.PersonagensArmas;
import tabelas.PersonagensConsumiveis;
import tabelas.PersonagensEscudos;

/**
 *
 * @author Felipe Ittner, Withoeft
 */
public class JFTrocaItens extends javax.swing.JFrame {

    /**
     * Creates new form JFTrocaCliente
     */
    public JFTrocaItens() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcArmasboxPlayer1 = new javax.swing.JComboBox();
        jcArmasboxPlayer2 = new javax.swing.JComboBox();
        jcArmadurasboxPlayer1 = new javax.swing.JComboBox();
        jcEscudosboxPlayer1 = new javax.swing.JComboBox();
        jcConsumiveisboxPlayer1 = new javax.swing.JComboBox();
        jcArmadurasboxPlayer2 = new javax.swing.JComboBox();
        jcEscudosboxPlayer2 = new javax.swing.JComboBox();
        jcConsumiveisboxPlayer2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jcbArmasPlayer1 = new javax.swing.JCheckBox();
        jcbArmadurasPlayer1 = new javax.swing.JCheckBox();
        jcbEscudosPlayer1 = new javax.swing.JCheckBox();
        jcbConsumiveisPlayer1 = new javax.swing.JCheckBox();
        jcbArmasPlayer2 = new javax.swing.JCheckBox();
        jcbArmadurasPlayer2 = new javax.swing.JCheckBox();
        jcbEscudosPlayer2 = new javax.swing.JCheckBox();
        jcbConsumiveisPlayer2 = new javax.swing.JCheckBox();
        lbVender = new javax.swing.JLabel();
        jlListPreçoTotalComprar = new javax.swing.JLabel();
        lbVender1 = new javax.swing.JLabel();
        jlListPreçoTotalComprar1 = new javax.swing.JLabel();
        jConfirmarPlayer2 = new javax.swing.JCheckBox();
        jConfirmarPlayer1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jcArmasboxPlayer1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcArmasboxPlayer1ItemStateChanged(evt);
            }
        });
        jcArmasboxPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcArmasboxPlayer1ActionPerformed(evt);
            }
        });

        jcArmasboxPlayer2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcArmasboxPlayer2ItemStateChanged(evt);
            }
        });
        jcArmasboxPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcArmasboxPlayer2ActionPerformed(evt);
            }
        });

        jcArmadurasboxPlayer1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcArmadurasboxPlayer1ItemStateChanged(evt);
            }
        });
        jcArmadurasboxPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcArmadurasboxPlayer1ActionPerformed(evt);
            }
        });

        jcEscudosboxPlayer1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcEscudosboxPlayer1ItemStateChanged(evt);
            }
        });
        jcEscudosboxPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcEscudosboxPlayer1ActionPerformed(evt);
            }
        });

        jcConsumiveisboxPlayer1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcConsumiveisboxPlayer1ItemStateChanged(evt);
            }
        });
        jcConsumiveisboxPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcConsumiveisboxPlayer1ActionPerformed(evt);
            }
        });

        jcArmadurasboxPlayer2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcArmadurasboxPlayer2ItemStateChanged(evt);
            }
        });

        jcEscudosboxPlayer2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcEscudosboxPlayer2ItemStateChanged(evt);
            }
        });

        jcConsumiveisboxPlayer2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcConsumiveisboxPlayer2ItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel1.setText("Tela de Troca");

        jcbArmasPlayer1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbArmasPlayer1.setText("Armas");
        jcbArmasPlayer1.setHideActionText(true);
        jcbArmasPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbArmasPlayer1ActionPerformed(evt);
            }
        });

        jcbArmadurasPlayer1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbArmadurasPlayer1.setText("Armaduras");
        jcbArmadurasPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbArmadurasPlayer1ActionPerformed(evt);
            }
        });

        jcbEscudosPlayer1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbEscudosPlayer1.setText("Escudos");
        jcbEscudosPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEscudosPlayer1ActionPerformed(evt);
            }
        });

        jcbConsumiveisPlayer1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbConsumiveisPlayer1.setText("Consumiveis");
        jcbConsumiveisPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbConsumiveisPlayer1ActionPerformed(evt);
            }
        });

        jcbArmasPlayer2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbArmasPlayer2.setText("Armas");
        jcbArmasPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbArmasPlayer2ActionPerformed(evt);
            }
        });

        jcbArmadurasPlayer2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbArmadurasPlayer2.setText("Armaduras");
        jcbArmadurasPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbArmadurasPlayer2ActionPerformed(evt);
            }
        });

        jcbEscudosPlayer2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbEscudosPlayer2.setText("Escudos");
        jcbEscudosPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEscudosPlayer2ActionPerformed(evt);
            }
        });

        jcbConsumiveisPlayer2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcbConsumiveisPlayer2.setText("Consumiveis");
        jcbConsumiveisPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbConsumiveisPlayer2ActionPerformed(evt);
            }
        });

        lbVender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbVender.setText("Personagem:");

        lbVender1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbVender1.setText("Personagem:");

        jConfirmarPlayer2.setText("Confirmar");
        jConfirmarPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConfirmarPlayer2ActionPerformed(evt);
            }
        });

        jConfirmarPlayer1.setText("Confirmar");
        jConfirmarPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConfirmarPlayer1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlListPreçoTotalComprar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbVender1)
                        .addGap(52, 52, 52)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlListPreçoTotalComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbVender)
                        .addGap(131, 131, 131))))
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcbArmadurasPlayer1)
                        .addGap(11, 11, 11)
                        .addComponent(jcArmadurasboxPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jcbArmadurasPlayer2)
                        .addGap(11, 11, 11)
                        .addComponent(jcArmadurasboxPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcbEscudosPlayer1)
                        .addGap(29, 29, 29)
                        .addComponent(jcEscudosboxPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jcbEscudosPlayer2)
                        .addGap(29, 29, 29)
                        .addComponent(jcEscudosboxPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcbConsumiveisPlayer1)
                        .addGap(3, 3, 3)
                        .addComponent(jcConsumiveisboxPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jcbConsumiveisPlayer2)
                        .addGap(3, 3, 3)
                        .addComponent(jcConsumiveisboxPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcbArmasPlayer1)
                        .addGap(37, 37, 37)
                        .addComponent(jcArmasboxPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jcbArmasPlayer2)
                        .addGap(37, 37, 37)
                        .addComponent(jcArmasboxPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jConfirmarPlayer1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jConfirmarPlayer2)
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbVender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlListPreçoTotalComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbVender1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlListPreçoTotalComprar1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbArmasPlayer1)
                    .addComponent(jcArmasboxPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbArmasPlayer2)
                    .addComponent(jcArmasboxPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbArmadurasPlayer1)
                    .addComponent(jcArmadurasboxPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbArmadurasPlayer2)
                    .addComponent(jcArmadurasboxPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbEscudosPlayer1)
                    .addComponent(jcEscudosboxPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbEscudosPlayer2)
                    .addComponent(jcEscudosboxPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbConsumiveisPlayer1)
                    .addComponent(jcConsumiveisboxPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbConsumiveisPlayer2)
                    .addComponent(jcConsumiveisboxPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jConfirmarPlayer2)
                    .addComponent(jConfirmarPlayer1))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcArmasboxPlayer1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcArmasboxPlayer1ItemStateChanged

    }//GEN-LAST:event_jcArmasboxPlayer1ItemStateChanged

    private void jcArmasboxPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcArmasboxPlayer1ActionPerformed

    }//GEN-LAST:event_jcArmasboxPlayer1ActionPerformed

    private void jcArmasboxPlayer2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcArmasboxPlayer2ItemStateChanged

    }//GEN-LAST:event_jcArmasboxPlayer2ItemStateChanged

    private void jcArmasboxPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcArmasboxPlayer2ActionPerformed

    }//GEN-LAST:event_jcArmasboxPlayer2ActionPerformed

    private void jcArmadurasboxPlayer1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcArmadurasboxPlayer1ItemStateChanged

    }//GEN-LAST:event_jcArmadurasboxPlayer1ItemStateChanged

    private void jcArmadurasboxPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcArmadurasboxPlayer1ActionPerformed

    }//GEN-LAST:event_jcArmadurasboxPlayer1ActionPerformed

    private void jcEscudosboxPlayer1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcEscudosboxPlayer1ItemStateChanged

    }//GEN-LAST:event_jcEscudosboxPlayer1ItemStateChanged

    private void jcEscudosboxPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcEscudosboxPlayer1ActionPerformed

    }//GEN-LAST:event_jcEscudosboxPlayer1ActionPerformed

    private void jcConsumiveisboxPlayer1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcConsumiveisboxPlayer1ItemStateChanged

    }//GEN-LAST:event_jcConsumiveisboxPlayer1ItemStateChanged

    private void jcConsumiveisboxPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcConsumiveisboxPlayer1ActionPerformed

    }//GEN-LAST:event_jcConsumiveisboxPlayer1ActionPerformed

    private void jcArmadurasboxPlayer2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcArmadurasboxPlayer2ItemStateChanged

    }//GEN-LAST:event_jcArmadurasboxPlayer2ItemStateChanged

    private void jcEscudosboxPlayer2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcEscudosboxPlayer2ItemStateChanged

    }//GEN-LAST:event_jcEscudosboxPlayer2ItemStateChanged

    private void jcConsumiveisboxPlayer2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcConsumiveisboxPlayer2ItemStateChanged

    }//GEN-LAST:event_jcConsumiveisboxPlayer2ItemStateChanged

    private void jcbArmasPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbArmasPlayer1ActionPerformed
        if (jcbArmasPlayer1.isSelected()) {
            jConfirmarPlayer1.setVisible(true);
        } else {
            jConfirmarPlayer1.setVisible(false);
        }
        
        GenericDAO gDao = null;
        
        try {
            gDao = new GenericDAO();
        } catch (SQLException ex) {
            Logger.getLogger(JFTrocaItens.class.getName()).log(Level.SEVERE, null, ex);
        }
        List<Object> list = null;

        

        try {
            list = gDao.listar(PersonagensArmas.class);
        } catch (SQLException | IllegalAccessException | NoSuchMethodException | IllegalArgumentException | InvocationTargetException | InstantiationException | ClassNotFoundException ex) {
            Logger.getLogger(JFTrocaItens.class.getName()).log(Level.SEVERE, null, ex);
        }

       

        for (Object obj2 : list) {

            PersonagensArmas armaNN = (PersonagensArmas) obj2; ////lista todos os codigos das armas da tabela N/N
            Armas arma = new Armas();
            List<Object> ListarArmas = new ArrayList<>();

            int codigoArma = (armaNN.getCodigo_arma());
            int codigoPersonagem = (armaNN.getCodigo_personagem());
            arma.setCodigo_arma(codigoArma);     /////seta o codigo da arma na tabela N/N
        }
    }//GEN-LAST:event_jcbArmasPlayer1ActionPerformed

    private void jcbArmadurasPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbArmadurasPlayer1ActionPerformed
        if (jcbArmadurasPlayer1.isSelected()) {
            jConfirmarPlayer1.setVisible(true);
        } else { 
            jConfirmarPlayer1.setVisible(false);
        }
        GenericDAO gDao = null;
        
        try {
            gDao = new GenericDAO();
        } catch (SQLException ex) {
            Logger.getLogger(JFTrocaItens.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        List<Object> list = null;

        try {
            list = gDao.listar(PersonagensArmaduras.class);
        } catch (SQLException | IllegalAccessException | NoSuchMethodException | IllegalArgumentException | InvocationTargetException | InstantiationException | ClassNotFoundException ex) {
            Logger.getLogger(JFTrocaItens.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (Object obj2 : list) {   ////lista todos os codigos das armaduras da tabela N/N

            PersonagensArmaduras armadurasNN = (PersonagensArmaduras) obj2;
            Armaduras armadura = new Armaduras();
            List<Object> ListarArmaduras = new ArrayList<>();

            int codigoArmadura = (armadurasNN.getCodigo_armadura());
            int codigoPersonagem = (armadurasNN.getCodigo_personagem());
            armadura.setCodigo_armadura(codigoArmadura);  /////seta o codigo da armadura na tabela N/N
        }    
    }//GEN-LAST:event_jcbArmadurasPlayer1ActionPerformed

    private void jcbEscudosPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEscudosPlayer1ActionPerformed
        if (jcbEscudosPlayer1.isSelected()) {
            jConfirmarPlayer1.setVisible(true);
        } else {
            jConfirmarPlayer1.setVisible(false);
        }
         GenericDAO gDao = null;
        
        try {
            gDao = new GenericDAO();
        } catch (SQLException ex) {
            Logger.getLogger(JFTrocaItens.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        List<Object> list = null;

        try {
            list = gDao.listar(PersonagensEscudos.class);
        } catch (SQLException | IllegalAccessException | NoSuchMethodException | IllegalArgumentException | InvocationTargetException | InstantiationException | ClassNotFoundException ex) {
            Logger.getLogger(JFTrocaItens.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (Object obj2 : list) {   ////lista todos os codigos dos escudos da tabela N/N

            PersonagensEscudos escudosNN = (PersonagensEscudos) obj2;
            Escudos escudo = new Escudos();
            List<Object> ListarEscudos = new ArrayList<>();

            int codigoEscudo = (escudosNN.getCodigo_escudo());
            int codigoPersonagem = (escudosNN.getCodigo_personagem());
            escudo.setCodigo_escudo(codigoEscudo);  /////seta o codigo do escudo na tabela N/N
        }
    }//GEN-LAST:event_jcbEscudosPlayer1ActionPerformed

    private void jcbConsumiveisPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbConsumiveisPlayer1ActionPerformed
        if (jcbConsumiveisPlayer1.isSelected()) {
            jConfirmarPlayer1.setVisible(true);
        } else {
            jConfirmarPlayer1.setVisible(false);
        }
        GenericDAO gDao = null;
        
        try {
            gDao = new GenericDAO();
        } catch (SQLException ex) {
            Logger.getLogger(JFTrocaItens.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        List<Object> list = null;

        try {
            list = gDao.listar(PersonagensConsumiveis.class);
        } catch (SQLException | IllegalAccessException | NoSuchMethodException | IllegalArgumentException | InvocationTargetException | InstantiationException | ClassNotFoundException ex) {
            Logger.getLogger(JFTrocaItens.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (Object obj2 : list) {   ////lista todos os codigos dos consumiveis da tabela N/N

            PersonagensConsumiveis consumiveisNN = (PersonagensConsumiveis) obj2;
            Consumiveis consumivel = new Consumiveis();
            List<Object> ListarConsumiveis = new ArrayList<>();

            int codigoConsumivel = (consumiveisNN.getCodigo_consumivel());
            int codigoPersonagem = (consumiveisNN.getCodigo_personagem());
            consumivel.setCodigo_consumivel(codigoConsumivel);  /////seta o codigo do consumivel na tabela N/N
        }
    }//GEN-LAST:event_jcbConsumiveisPlayer1ActionPerformed

    private void jcbArmasPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbArmasPlayer2ActionPerformed
        jcbArmasPlayer2.setEnabled(false);
        jcArmasboxPlayer2.setEnabled(false);
    }//GEN-LAST:event_jcbArmasPlayer2ActionPerformed

    private void jcbArmadurasPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbArmadurasPlayer2ActionPerformed
        jcbArmadurasPlayer2.setEnabled(false);
        jcArmadurasboxPlayer2.setEnabled(false);
    }//GEN-LAST:event_jcbArmadurasPlayer2ActionPerformed

    private void jcbEscudosPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEscudosPlayer2ActionPerformed
        jcbEscudosPlayer2.setEnabled(false);
        jcEscudosboxPlayer2.setEnabled(false);
    }//GEN-LAST:event_jcbEscudosPlayer2ActionPerformed

    private void jcbConsumiveisPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbConsumiveisPlayer2ActionPerformed
        jcbConsumiveisPlayer2.setEnabled(false);
        jcConsumiveisboxPlayer2.setEnabled(false);
    }//GEN-LAST:event_jcbConsumiveisPlayer2ActionPerformed

    private void jConfirmarPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConfirmarPlayer2ActionPerformed
        jConfirmarPlayer2.setEnabled(false);
    }//GEN-LAST:event_jConfirmarPlayer2ActionPerformed

    private void jConfirmarPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConfirmarPlayer1ActionPerformed
        jConfirmarPlayer1.setVisible(true);
    }//GEN-LAST:event_jConfirmarPlayer1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFTrocaItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFTrocaItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFTrocaItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFTrocaItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFTrocaItens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jConfirmarPlayer1;
    private javax.swing.JCheckBox jConfirmarPlayer2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox jcArmadurasboxPlayer1;
    private javax.swing.JComboBox jcArmadurasboxPlayer2;
    private javax.swing.JComboBox jcArmasboxPlayer1;
    private javax.swing.JComboBox jcArmasboxPlayer2;
    private javax.swing.JComboBox jcConsumiveisboxPlayer1;
    private javax.swing.JComboBox jcConsumiveisboxPlayer2;
    private javax.swing.JComboBox jcEscudosboxPlayer1;
    private javax.swing.JComboBox jcEscudosboxPlayer2;
    private javax.swing.JCheckBox jcbArmadurasPlayer1;
    private javax.swing.JCheckBox jcbArmadurasPlayer2;
    private javax.swing.JCheckBox jcbArmasPlayer1;
    private javax.swing.JCheckBox jcbArmasPlayer2;
    private javax.swing.JCheckBox jcbConsumiveisPlayer1;
    private javax.swing.JCheckBox jcbConsumiveisPlayer2;
    private javax.swing.JCheckBox jcbEscudosPlayer1;
    private javax.swing.JCheckBox jcbEscudosPlayer2;
    private javax.swing.JLabel jlListPreçoTotalComprar;
    private javax.swing.JLabel jlListPreçoTotalComprar1;
    private javax.swing.JLabel lbVender;
    private javax.swing.JLabel lbVender1;
    // End of variables declaration//GEN-END:variables
}
